### ISSUE TITLE
Unable to locate "existence_benchmark.test_mturk.json"

### ISSUE THREAD

**Issue by farisxiong** [Heidelberg-NLP/MM-SHAP#1]
## Description:
I'm currently working on MM-Shap and I'm in need of the file existence_benchmark.test_mturk.json.  Can someone provide guidance on how to obtain this file or is there a specific procedure to generate it?

if I use the existence.json in VALSE, it also reminder me that "test_sentences = [foil["caption"], foil["foils"][0]]
KeyError: 'foils'"

**Comment by LetiP** [comment]
Hello, thanks for the question. The scripts here intend to show the usage and provide the code for calculating MM-SHAP and you might need to adjust the script for the data format you are working with.

The data you are referring to in this issue originates from our previous project on VALSE: https://github.com/Heidelberg-NLP/VALSE/

You can find the data [here](https://github.com/Heidelberg-NLP/VALSE/tree/main/data), therefore we did not add it into this repository as well.

Keep in mind that when publishing the VALSE data we did some cleanups for publications which might not be reflected in the scripts for MM-SHAP:

- the filename for the existence data is a bit cleaner in the VALSE repository, namely just `existence.json`
- You need to change the key `foils` in the code to `foil` to adapt to the format of the published VALSE data.
- Since there is only one foil and not many foils, you need to delete the `[0]` indexing there, so `test_sentences = [foil["caption"], foil["foil"]]` should do the trick.
